### ISSUE TITLE
Rancher-CLI

### ISSUE THREAD

**Issue by cloudlady911** [badouralix/dockerfiles#1]
I am using the Rancher-CLI image to run a command to stop a container.  It works. Yay! but then it doesn't stop afterward.  The job in Gitlab just keeps running.

```
stop-container:
  stage: stop-container
  tags:
    - docker
  image: badouralix/rancher-cli
  script:
   - rancher --wait stop stackname/$CI_PROJECT_NAME
```

This is the log
`Running with gitlab-runner 10.6.0 (a3543a27)
  on docker-s3 b0cb8b71
Using Docker executor with image badouralix/rancher-cli ...
Pulling docker image badouralix/rancher-cli ...
Using docker image sha256:15d86bc353a6a5e54873bf6d96273224d57516e74ac2d8402a828abcc593239c for badouralix/rancher-cli ...
Running on runner-b0cb8b71-project-484-concurrent-0 via b799faebbb54...
Fetching changes...
HEAD is now at b1c39a7 Update .gitlab-ci.yml
Checking out b1c39a7b as master...
Skipping Git submodules setup
$ rancher --wait stop scraper/$CI_PROJECT_NAME
1s381
. . .
`
